### ISSUE TITLE
Question : Exact Match computation

### ISSUE THREAD

**Issue by Geethi2020** [deepset-ai/COVID-QA#175]
Hello, Would you please help understand how the "Exact Match" is calculated? May be please point to which .py file to be referred for the code. Thank you

**Comment by Timoeller** [comment]
Exact match is the exact match between two strings, only if their are equal it is 1, otherwise 0.
Some scripts exclude punctuation, multiple whitespace and stopwords from the exact match calculation. See [here](https://github.com/deepset-ai/FARM/blob/master/farm/evaluation/squad_evaluation.py#L78) this is the official SQuAD eval script (in our framework FARM)

**Comment by Geethi2020** [comment]
Thank you for the response and thank so very much for the dataset.
