### ISSUE TITLE
Train BERT on Quora Question Pairs Dataset

### ISSUE THREAD

**Issue by brandenchan** [deepset-ai/COVID-QA#18]
Using Sentence Transformers (https://github.com/UKPLab/sentence-transformers) I will start training a model on the Quora Question Pairs Dataset (https://www.kaggle.com/c/quora-question-pairs) that can classify duplicate question pairs.

**Comment by brandenchan** [comment]
Model is trained and can be found in the aws s3 bucket “deepset.ai-farm-models/covid-hackathon/bert_base_quora_dedup.” It contains the script used to train it, a readme and dev metrics

**Comment by tholor** [comment]
Great! can you please create a PR for the training code. It could go into here https://github.com/deepset-ai/COVID-QA/tree/master/covid-qa/modeling/transformer

Would be also nice if you could do a quick run on our English eval dataset and report metrics here / in mlflow (see example script [here](https://github.com/deepset-ai/COVID-QA/blob/master/covid-qa/modeling/transformer/eval_pretrained_haystack.py))

**Comment by tholor** [comment]
Turns out the embeddings from the model trained on Quora dataset are actually not performing that well on our eval dataset (see https://public-mlflow.deepset.ai/#/experiments/55/runs/57074b3298e443b89adc5c0bed8590e4). Possibly the questions are there are too far off from our domain or the definition of "duplicate questions" is different there.
